<a href="https://colab.research.google.com/github/nagendrap418/ds_linear/blob/main/bank(logistic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [ ]:
bank=pd.read_csv('bank-full.csv',header=None,sep =';' )
bank.head()

In [ ]:
bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69791 entries, 0 to 69790
Data columns (total 1 columns):
 #   Column                                                                                                                                                Non-Null Count  Dtype 
---  ------                                                                                                                                                --------------  ----- 
 0   age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"  69791 non-null  object
dtypes: object(1)
memory usage: 545.4+ KB


In [ ]:
bank.shape

(45211, 17)

In [ ]:
X = bank.iloc[:,1:]
Y = bank.iloc[:,0]

In [ ]:
categorical = [var for var in bank.columns if bank[var].dtype=='O']
print('There are {} categorical variables\n'.format(len(categorical)))
print('categorical variables are:', categorical)

There are 10 categorical variables

categorical variables are: ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome', 'y']


In [ ]:
bank[categorical].isnull().sum()

job          0
marital      0
education    0
default      0
housing      0
loan         0
contact      0
month        0
poutcome     0
y            0
dtype: int64

In [ ]:
bank=pd.get_dummies(bank,columns=['job','marital','education','contact','month','poutcome'])

In [ ]:
bank['default'] = np.where(bank['default'].str.contains('yes'),1,0)
bank['housing'] = np.where(bank['housing'].str.contains('yes'),1,0)
bank['loan'] = np.where(bank['loan'].str.contains('yes'),1,0)
bank['y']= np.where(bank['y'].str.contains('yes'),1,0)
bank

age  default  balance  housing  loan  day  duration  campaign  pdays  \
0       58        0     2143        1     0    5       261         1     -1   
1       44        0       29        1     0    5       151         1     -1   
2       33        0        2        1     1    5        76         1     -1   
3       47        0     1506        1     0    5        92         1     -1   
4       33        0        1        0     0    5       198         1     -1   
...    ...      ...      ...      ...   ...  ...       ...       ...    ...   
45206   51        0      825        0     0   17       977         3     -1   
45207   71        0     1729        0     0   17       456         2     -1   
45208   72        0     5715        0     0   17      1127         5    184   
45209   57        0      668        0     0   17       508         4     -1   
45210   37        0     2971        0     0   17       361         2    188   

       previous  ...  month_jun  month_mar  month_may  month_nov  month_oct  \
0             0  ...          0          0          1          0          0   
1             0  ...          0          0          1          0          0   
2             0  ...          0          0          1          0          0   
3             0  ...          0          0          1          0          0   
4             0  ...          0          0          1          0          0   
...         ...  ...        ...        ...        ...        ...        ...   
45206         0  ...          0          0          0          1          0   
45207         0  ...          0          0          0          1          0   
45208         3  ...          0          0          0          1          0   
45209         0  ...          0          0          0          1          0   
45210        11  ...          0          0          0          1          0   

       month_sep  poutcome_failure  poutcome_other  poutcome_success  \
0              0                 0               0                 0   
1              0                 0               0                 0   
2              0                 0               0                 0   
3              0                 0               0                 0   
4              0                 0               0                 0   
...          ...               ...             ...               ...   
45206          0                 0               0                 0   
45207          0                 0               0                 0   
45208          0                 0               0                 1   
45209          0                 0               0                 0   
45210          0                 0               1                 0   

       poutcome_unknown  
0                     1  
1                     1  
2                     1  
3                     1  
4                     1  
...                 ...  
45206                 1  
45207                 1  
45208                 0  
45209                 1  
45210                 0  

[45211 rows x 49 columns]

In [ ]:
bank.iloc[:,15:30]

job_management  job_retired  job_self-employed  job_services  \
0                   1            0                  0             0   
1                   0            0                  0             0   
2                   0            0                  0             0   
3                   0            0                  0             0   
4                   0            0                  0             0   
...               ...          ...                ...           ...   
45206               0            0                  0             0   
45207               0            1                  0             0   
45208               0            1                  0             0   
45209               0            0                  0             0   
45210               0            0                  0             0   

       job_student  job_technician  job_unemployed  job_unknown  \
0                0               0               0            0   
1                0               1               0            0   
2                0               0               0            0   
3                0               0               0            0   
4                0               0               0            1   
...            ...             ...             ...          ...   
45206            0               1               0            0   
45207            0               0               0            0   
45208            0               0               0            0   
45209            0               0               0            0   
45210            0               0               0            0   

       marital_divorced  marital_married  marital_single  education_primary  \
0                     0                1               0                  0   
1                     0                0               1                  0   
2                     0                1               0                  0   
3                     0                1               0                  0   
4                     0                0               1                  0   
...                 ...              ...             ...                ...   
45206                 0                1               0                  0   
45207                 1                0               0                  1   
45208                 0                1               0                  0   
45209                 0                1               0                  0   
45210                 0                1               0                  0   

       education_secondary  education_tertiary  education_unknown  
0                        0                   1                  0  
1                        1                   0                  0  
2                        1                   0                  0  
3                        0                   0                  1  
4                        0                   0                  1  
...                    ...                 ...                ...  
45206                    0                   1                  0  
45207                    0                   0                  0  
45208                    1                   0                  0  
45209                    1                   0                  0  
45210                    1                   0                  0  

[45211 rows x 15 columns]

In [ ]:
X = bank.drop(columns='y')
X

age  default  balance  housing  loan  day  duration  campaign  pdays  \
0       58        0     2143        1     0    5       261         1     -1   
1       44        0       29        1     0    5       151         1     -1   
2       33        0        2        1     1    5        76         1     -1   
3       47        0     1506        1     0    5        92         1     -1   
4       33        0        1        0     0    5       198         1     -1   
...    ...      ...      ...      ...   ...  ...       ...       ...    ...   
45206   51        0      825        0     0   17       977         3     -1   
45207   71        0     1729        0     0   17       456         2     -1   
45208   72        0     5715        0     0   17      1127         5    184   
45209   57        0      668        0     0   17       508         4     -1   
45210   37        0     2971        0     0   17       361         2    188   

       previous  ...  month_jun  month_mar  month_may  month_nov  month_oct  \
0             0  ...          0          0          1          0          0   
1             0  ...          0          0          1          0          0   
2             0  ...          0          0          1          0          0   
3             0  ...          0          0          1          0          0   
4             0  ...          0          0          1          0          0   
...         ...  ...        ...        ...        ...        ...        ...   
45206         0  ...          0          0          0          1          0   
45207         0  ...          0          0          0          1          0   
45208         3  ...          0          0          0          1          0   
45209         0  ...          0          0          0          1          0   
45210        11  ...          0          0          0          1          0   

       month_sep  poutcome_failure  poutcome_other  poutcome_success  \
0              0                 0               0                 0   
1              0                 0               0                 0   
2              0                 0               0                 0   
3              0                 0               0                 0   
4              0                 0               0                 0   
...          ...               ...             ...               ...   
45206          0                 0               0                 0   
45207          0                 0               0                 0   
45208          0                 0               0                 1   
45209          0                 0               0                 0   
45210          0                 0               1                 0   

       poutcome_unknown  
0                     1  
1                     1  
2                     1  
3                     1  
4                     1  
...                 ...  
45206                 1  
45207                 1  
45208                 0  
45209                 1  
45210                 0  

[45211 rows x 48 columns]

In [ ]:
y_bank = bank.loc[:,'y']
y_bank
y_bank.unique()

array([0, 1])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y_bank,test_size=0.3)
X_train, X_test, y_train, y_test

(       age  default  balance  housing  loan  day  duration  campaign  pdays  \
 28638   39        0       33        0     0   29       593         4     -1   
 37837   34        0       28        1     0   14       175         1    358   
 9836    58        0     1382        0     0    9       700         1     -1   
 15438   34        0     -251        0     0   18       641         1     -1   
 24918   41        0     1100        1     0   18       397         1    173   
 ...    ...      ...      ...      ...   ...  ...       ...       ...    ...   
 5519    46        0      772        1     0   23       488         1     -1   
 17753   43        0       -7        1     1   29       228         1     -1   
 38566   24        0      513        1     0   15        61         3     -1   
 40902   55        0      113        0     0   12       306         1    457   
 42663   48        0      517        0     0   14       273         1     -1   
 
        previous  ...  month_jun  mont

In [ ]:
logistic_model = LogisticRegression()
logistic_model.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [ ]:
y_pred = logistic_model.predict(X_train)

y_pred_test = logistic_model.predict(X_test)

In [ ]:
y_pred_df

actual  predicted_prob
0          58               0
1          44               0
2          33               0
3          47               0
4          33               0
...       ...             ...
45206      51               1
45207      71               0
45208      72               1
45209      57               0
45210      37               0

[45211 rows x 2 columns]

In [ ]:
confusion_matrix(y_train,y_pred)

array([[27430,   537],
       [ 2898,   782]])

In [ ]:
confusion_matrix(y_test,y_pred_test)

array([[11735,   220],
       [ 1260,   349]])

In [ ]:
print((31340+868)/(31340+590+3370+868))
print(accuracy_score(y_train,y_pred))

0.8905109489051095
0.8914589060574462


In [ ]:
print(accuracy_score(y_test,y_pred_test))

0.8908876437629017


In [ ]:
print(classification_report(y_train,y_pred))

              precision    recall  f1-score   support

           0       0.90      0.98      0.94     27967
           1       0.59      0.21      0.31      3680

    accuracy                           0.89     31647
   macro avg       0.75      0.60      0.63     31647
weighted avg       0.87      0.89      0.87     31647



In [ ]:
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.90      0.98      0.94     11955
           1       0.61      0.22      0.32      1609

    accuracy                           0.89     13564
   macro avg       0.76      0.60      0.63     13564
weighted avg       0.87      0.89      0.87     13564



In [ ]:
from pickle import dump,load
logistic_model.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0])